version: 2
updates:
  - package-ecosystem: "pip"
    directories: "**/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories: "**/*"
    schedule:
      interval: "weekly"
